id: ctf
name: CTF
description: Tackle the levels to practice your hacking skills
courses:
  - name: level-0
    description: Pass these simple, single action challenges
  - name: level-1
    description: Go deeper with flags which require multiple steps
  - name: level-2
    description: Multiple steps and tools are needed to capture these flags