T1547.002:
  metadata:
    description: Dropper and payload for T1547.002
    purpose: payloads
  payloads:
    package:
      build: |
        cl.exe /W1 package.c package.def /MT /link /DLL /OUT:package.dll
    install:
      build: |
        dotnet publish -c Release -r win-x64