id: pink
name: Pink Badge
description: A self-paced class to learn cybersecurity
courses:
  - name: registration
    description: Start here to register for the program
    challenges:
      - ed2e1bae-5f2f-429d-9760-4dea63d650e1
  - name: week-1
    description: Learn about the various components that make up security
    challenges:
      - 03e3e43c-4cb3-4267-bfa9-4d0f63762032
      - 83a3ca9e-6e32-4c67-b2f6-1a38970db09a
      - c42b9ff5-20b9-45c7-9289-ec7c4aee6fd8
      - cceab224-9179-4e02-b7cd-96fe2f1bb001
      - f437e5f4-669f-4d71-87cb-517d6266d8eb
      - 2f70a23f-b2d0-4942-b1e9-9a7176895119
  - name: week-2
    description: 'Get your feet wet with agents, attacks and adversaries'
    challenges:
      - 54527f15-6d11-4ead-857e-6644642fc9e1
      - 9e5c7ba2-15f8-4bd8-b539-75204cfe7fda
  - name: week-3
    description: Learn how to convert security results into action
    challenges:
      - 04ceaeb4-db4a-4411-a75d-7baaf9e77984
      - 5b94b4df-6fcd-45c8-9c32-01599a2a1d44
      - d263aa1d-12ec-40f2-9166-fbf80fe1ed4a
      - e51816a2-1172-4eeb-916a-54845d12d265
  - name: final-project
    description: Your final project - running a real security test
    challenges:
      - 5e76bb42-fced-4389-9685-7b53b05b6ddf