id: protect
name: Protect Mode
description: Training modules to accompany autonomous Protect Mode chains
courses:
  - name: collection
    description: The adversary is trying to collect information from your system
  - name: command-and-control
    description: The adversary is trying to control agents, ingress tools, and remotely control your system
  - name: credential-access
    description: The adversary is trying to access passwords, tokens, and other forms of credentials
  - name: execution
    description: The adversary is trying to run malicious code
  - name: impact
    description: The adversary is trying to manipulate, interrupt, or destroy your systems and data
  - name: initial-access
    description: The adversary is trying to get into your network
